version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://bercario_noite_owner:YAULD59eaGEq@ep-lively-lake-a5t9ijax.us-east-2.aws.neon.tech/gerenciadorjogos?sslmode=require"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: bercario_noite_owner
      POSTGRES_PASSWORD: YAULD59eaGEq
      POSTGRES_DB: gerenciadorjogos
    ports:
      - "5432:5432"
